name: skillcraft
services:
  skillcraft_frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: skillcraft_frontend
    container_name: SkillCraft_frontend
    restart: unless-stopped
    ports:
      - 18088:80
