name: Publish SkillCraftRPG Website

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish:
    name: Publish SkillCraftRPG Website
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Extract Metadata (Tags, Labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: skillcraftrpg/www

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          file: frontend/Dockerfile
          context: ./frontend
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
